-- 1. ALTER TABLE

-- 2. CREATE INDEX

-- 3. INSERT INTO

-- 4. UPDATE

-- 5. DELETE

-- 6. SELECT FROM WHERE
SELECT F.SALARIO FROM FUNCIONARIO F
WHERE F.TURNO_DE_TRABALHO = 'Tarde';

-- 7. BETWEEN
SELECT F.CPF_FUNCIONARIO FROM FUNCIONARIO F
WHERE SALARIO BETWEEN 1499 AND 2501;

-- 8. IN
SELECT NOME, BAIRRO, CIDADE FROM PESSOA P
WHERE P.CIDADE IN ('Recife', 'Olinda');


-- 9. LIKE
SELECT P.NOME
FROM PESSOA P, FUNCIONARIO F
WHERE P.CPF = F.CPF_FUNCIONARIO
AND F.TURNO_DE_TRABALHO LIKE 'Tarde';

-- 10. IS NULL / IS NOT NULL
SELECT CPF_PILOTO, HORAS_DE_VOO FROM PILOTO P
WHERE P.CPF_COPILOTO IS NULL;

-- 11. INNER JOIN

-- 12. MAX

-- 13. MIN

-- 14. AVG
SELECT AVG (CLIENTES_ATENDIDOS) FROM ATENDENTE;

-- 15. COUNT
SELECT COUNT (*) FROM PILOTO
WHERE HORAS_DE_VOO > 10000;

-- 16. LEFT / RIGHT / FULL OUTER JOIN

-- 17. Subconsulta com operador relacional

-- 18. Subconsulta com IN

-- 19. Subconsulta com ANY

-- 20. SUBCONSULTA COM ALL

-- 21. ORDER BY
SELECT F.SALARIO, P.NOME
FROM FUNCIONARIO F, PESSOA P
WHERE F.CPF_FUNCIONARIO = P.CPF
ORDER BY F.SALARIO DESC;

-- 22. GROUP BY
SELECT F.TURNO_DE_TRABALHO, COUNT(*)
FROM FUNCIONARIO F
GROUP BY TURNO_DE_TRABALHO;

-- 23. HAVING
SELECT F.TURNO_DE_TRABALHO, COUNT(*)
FROM FUNCIONARIO F
WHERE SALARIO BETWEEN 1000 AND 2500 
GROUP BY F.TURNO_DE_TRABALHO
HAVING COUNT(*) > 1;

-- 24. UNION ou INTERSECT ou MINUS

-- 25. CREATE VIEW

-- 26. GRANT / REVOKE